### ISSUE TITLE
Addition of a github maven repo?

### ISSUE THREAD

**Issue by mjw99** [BlueObelisk/wwmm-pom#2]
Hi Oliver,

Looking at commit c815e60e, it would appear that you have introduced another maven repository, a github one (via the <repositories> element), to the dependency chain. I am not sure if this was intended or not.

I would not recommend doing this; it essentially prevents deployment to Maven Central (see [here](https://central.sonatype.org/pages/requirements.html) ). In addition, this split repository approach is partly the reason why so many of these deployed artifacts lay trapped on the local maven.ch.cam.ac.uk maven server and now have been essentially lost.

I have a set of instructions somewhere on how to carry out a deploy to maven central via sonatype staging, using the [mvn release plugin](https://maven.apache.org/maven-release/maven-release-plugin/). A few people IIRC, including me and PMR can deploy to this. I will try to dig these instructions out and see if I can add you to this.

In the meantime, I suggest we move to a wwmm-pom-6, removing this <repositories> element and I will deploy to maven central via sonatype staging. What do you think?

**Comment by ostueker** [comment]
Thanks Mark, that all sounds good to me.

In hindsight I shouldn't have used this (or any other live) repo for my experiments with deploying to the GitHub maven repo.

**Comment by mjw99** [comment]
Great; I'll proceed and try to get you those instructions. Do you know if there a wiki function associated with this repo?

**Comment by ostueker** [comment]
I've initialized the wiki and elevated the WWMM-group's permissions to the associated repos.

**Comment by ostueker** [comment]
I found the guides for Sonatype's deploy to staging:
* https://central.sonatype.org/pages/ossrh-guide.html
* https://central.sonatype.org/pages/releasing-the-deployment.html

and created a Jira account with my GitHub username.

**Comment by mjw99** [comment]
OK, [6](https://search.maven.org/artifact/uk.ac.cam.ch.wwmm/wwmm-parent/6/pom) is live now. I will update the instructions soon.

**Comment by mjw99** [comment]
Instructions [done](https://github.com/BlueObelisk/wwmm-pom/wiki/Deploying-a-project-to-Maven-Central-via-Sonatype-staging) ; will raise a ticket with Sonatype re your access soon.

**Comment by mjw99** [comment]
Sonatype ticket [raised](https://issues.sonatype.org/browse/OSSRH-54246)

**Comment by ostueker** [comment]
Thank you!

It seems that Sonatype allows to publish snapshots as well:
* [Documentation "Performing a Snapshot Deployment"](https://central.sonatype.org/pages/apache-maven.html#performing-a-snapshot-deployment) (search for "snapshots" on that page to find bits and snippets to be included to `pom.xml` and `settings.xml`.
* [uk.ac.cam.ch in snaptshots repo ](https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~uk/ac/cam/ch/)
* [CDK snaptshots repo ](https://oss.sonatype.org/#view-repositories;snapshots~browsestorage~org/openscience/cdk/)

What I'm thinking is something around the lines of:
* add this to the `pom.xml`:  
```xml
<distributionManagement>
  <snapshotRepository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/content/repositories/snapshots</url>
  </snapshotRepository>
  <repository>
    <id>ossrh</id>
    <url>https://oss.sonatype.org/service/local/staging/deploy/maven2/</url>
  </repository>
</distributionManagement>
```
* create a `.travis.settings.xml` with something like this: [travis.settings.txt](https://github.com/BlueObelisk/wwmm-pom/files/4016707/travis.settings.txt)
* Have Travis do a `cp .travis.settings.xml $HOME/.m2/settings.xml` to be able to pull snapshot releases from the ossrh-snapshots repo. 
This avoids that we need to add a `<repositories>` section within the `pom.xml` and remove it before doing a proper release.  
At the same time we keep the flexibility of being able to use un-released versions of some libraries in downstream projects for CI.

* The Blog post [How to Deploy Maven Artifacts with Travis CI and packagecloud](https://blog.travis-ci.com/2017-03-30-deploy-maven-travis-ci-packagecloud/) contains some tips how to publish Maven-Snapshot from within Travis jobs. Maybe we should look into using packagecloud for snapshot releases instead of Sonatype as the former seems to support authentication via Tokens instead of the per-user passwords used by Sonatype.

**Comment by mjw99** [comment]
OK, great! I did not know about this. Sounds like a really useful way forward.

**Comment by ostueker** [comment]
I noticed that there are also a number of projects that have a `groupID` of `org.xml-cml` (or some sub-domain of it -- see full list below).  

That raises two questions:

1. Who has privileges to deploy to `groupID: org.xml-cml`?
2. Should we consider to consolidate the packages under one groupID? 
   Maybe  `org.xml-cml` or `com.github.BlueObelisk` or `org.openscience.cml`/`org.openscience.wwmm` ? (I'm just thinking out loud)


----

Project | groupID
---------| ----------
cifxom |  
acpgeo | ACPGeo 
chemicaltagger-webapp | chemicalTagger 
chemtreebank | cml 
jumbo-converters | cml 
cmlxom | org.xml-cml 
euclid | org.xml-cml 
euclid-testutil | org.xml-cml 
html | org.xml-cml 
jumbo6 | org.xml-cml 
jumbo-inchi | org.xml-cml 
jumbo-testutil | org.xml-cml 
svg | org.xml-cml 
xml-cml.org | org.xml-cml 
cmllite-validator-code | org.xml-cml.validator 
cmllite-validator-ws | org.xml-cml.validator 
chemicaltagger | uk.ac.cam.ch.wwmm 
crystaleye | uk.ac.cam.ch.wwmm 
http-crawler | uk.ac.cam.ch.wwmm 
pub-crawler | uk.ac.cam.ch.wwmm 
wwmm-pom | uk.ac.cam.ch.wwmm 
oscar4-chebi | uk.ac.cam.ch.wwmm.oscar 
oscar4-cli | uk.ac.cam.ch.wwmm.oscar 
oscar4-taverna | uk.ac.cam.ch.wwmm.oscar 
oscar4-uima | uk.ac.cam.ch.wwmm.oscar 
oscar4 | uk.ac.cam.ch.wwmm.oscar

**Comment by mjw99** [comment]
I am not sure about the groupID: org.xml-cml ; I have never deployed to this. I think you'll have to ping @petermr

**Comment by ostueker** [comment]
In the OSSRH ticket database I have found: https://issues.sonatype.org/browse/OSSRH-1911
which is the only item that mentions `org.xml-cml`.  Does anyone have current coordinates of  David Jessop?

**Comment by mjw99** [comment]
David Jessop was a PhD student of PMR; he worked on [OSCAR4](http://dx.doi.org/10.1186/1758-2946-3-41). I am not sure where he is now.

**Comment by mjw99** [comment]
Sonatype access for @ostueker to uk.ac.cam.ch.wwmm is [resolved](https://issues.sonatype.org/browse/OSSRH-54246)
